Leave off --root if DESTDIR is not defined.
I got this error (note lack of leading slash on the installation
directory):

python setup-common.py install --root=
running install
Checking .pth file support in usr/local/lib/python2.7/dist-packages/
/usr/bin/python -E -c pass
TEST FAILED: usr/local/lib/python2.7/dist-packages/ does NOT support .pth files
error: bad install directory or PYTHONPATH