a2ensite insisted on having the ".conf".
# a2ensite fp-facilitator
ERROR: Site fp-facilitator does not exist!
# a2ensite fp-facilitator.conf
Enabling site fp-facilitator.conf.
To activate the new configuration, you need to run:
  service apache2 reload